run:
  timeout: 5m
linters:
  enable:
    # - depguard
    - dupl
    - exportloopref
    - gocyclo
    - gosec
    - gocritic
    - goconst
    - importas
    - gosimple
    - staticcheck
    - unused
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - unconvert
    - tenv
    - testpackage
    - thelper
    - godot
    - gofmt
    - goimports
    - misspell
    - gofumpt
    - whitespace
